[env]
# Load env from the dotenv file after tools have defined environment variables
_.file = { path = ".env", tools = true }

[tools]
############################################################
# cli
############################################################
starship = "latest" # shell prompt
ripgrep = "latest"
zellij = "latest"
fzf = "latest"
bat = "latest"
bat-extras = "latest"
eza = "latest"
fd = "latest"
dust = "latest" # like du but more intuitive
ctop = "latest"
dt = "latest"
duf = "latest"
rclone = "latest"
zoxide = "latest" # cd on steroids
yazi = "latest" # file manager
usage = "latest"
neovim = "latest" # text editor / ide
helix = "latest" # text editor / ide
restic = "latest" # backup tool
borg = "latest" # backup tool
lazyssh = "latest"
"npm:tldr" = "latest" # community-driven, simplified man pages
glow = "latest" # render markdown on CLI
marp-cli = "latest" # markdown slides
trivy = "latest" # vuln scanner
############################################################
# docker and k8s
############################################################
dive = "latest" # explore docker images
lazydocker = "latest"
colima = "latest"
lima = "latest"
kubectl = "latest"
kustomize = "latest"
krew = "latest"
kubecm = "latest"
kubie = "latest"
kubeshark = "latest"
kubespy = "latest"
kubeswitch = "latest"
k9s = "latest"
minikube = "latest"
############################################################
# git
############################################################
lazygit = "latest"
git-lfs = "latest"
gitu = "latest"
############################################################
# dev tools
############################################################
grpcurl = "latest" # graphql client
xh = "latest" # http client
websocat = "latest" # websocket client
bombardier = "latest" # http benchmarking tool
mkcert = "latest" # local https dev
just = "latest" # modern make
meson = "latest"
ninja = "latest"
jq = "latest"
yq = "latest"
jj = "latest" # SCM
############################################################
# language runtimes, compilers and LSP servers
############################################################
node = "lts"
bun = "latest"
uv = "latest" # Python
dotnet = "latest"
go = "latest"
rust = "latest"
rustic = "latest"
rust-analyzer = "latest"
zig = "latest"
java = "23.0.2"
janet = "latest"
lua-language-server = "latest"
zls = "latest" # zig language server
"npm:prettier" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:fish-lsp" = "latest"
"npm:@prisma/language-server" = "latest"
"npm:intelephense" = "latest"
"npm:eslint" = "latest"
"npm:pyright" = "latest"
ruff = "latest"
protobuf = "latest"
tree-sitter = "latest"
marksman = "latest" # markdown language server
"pipx:harlequin" = "latest" # cli database client
############################################################
# ops
############################################################
opentofu = "latest"
helm = "latest"
dagger = "latest"
############################################################
# cloud
############################################################
aws-cli = "latest"
doctl = "latest"
flyctl = "latest"
github-cli = "latest"
"pipx:snowflake-cli" = "latest"
############################################################
# other
############################################################
arduino = "latest"
